# Generated by Django 4.0.1 on 2022-01-27 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('-created_date',), 'verbose_name_plural': 'Notes'},
        ),
        migrations.RenameField(
            model_name='note',
            old_name='created',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='updated',
            new_name='updated_date',
        ),
    ]
