# Generated by Django 4.0.1 on 2022-01-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_options_rename_created_note_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='author',
            field=models.CharField(default='admin', max_length=255),
        ),
    ]
